### ISSUE TITLE
KEKLOL

### ISSUE THREAD

**Issue by maxutka99** [maksalees/FloweyBot#2]
This is very cool bot!!1 xD

**Comment by maksalees** [comment]
This is a pretty cool issue! But they are not intended for reviews :D

**Comment by maxutka99** [comment]
:(

**Comment by kirilojiq091** [comment]
Можно как то с тобой лично связаться?

**Comment by maksalees** [comment]
> Можно как то с тобой лично связаться?

Зачем?
